/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hellojni_AES */

#ifndef _Included_com_example_hellojni_AES
#define _Included_com_example_hellojni_AES
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hellojni_AES
 * Method:    AES_Encrypt
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_hellojni_AES_AES_1Encrypt
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_example_hellojni_AES
 * Method:    AES_Decrypt
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_hellojni_AES_AES_1Decrypt
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
